# Generated by Django 4.0 on 2023-04-25 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_number', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('receipt_number', models.CharField(max_length=12, null=True)),
                ('server', models.CharField(max_length=20, null=True)),
                ('server_name', models.CharField(max_length=40, null=True)),
                ('sub_total', models.IntegerField(null=True)),
                ('VAT', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('items', models.ManyToManyField(to='ReceiptGeneration.Item')),
            ],
        ),
    ]
