# Generated by Django 4.0 on 2023-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptGeneration', '0002_receipt_overseer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='overseer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
