# Generated by Django 4.0 on 2023-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptGeneration', '0005_receipt_till_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
