# Generated by Django 4.0 on 2023-05-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceiptGeneration', '0007_alter_receipt_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='till_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
