# Generated by Django 4.0 on 2023-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
