# Generated by Django 4.0 on 2023-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.TextField(null=True),
        ),
    ]
