# Generated by Django 4.0 on 2023-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee_id',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
