# Generated by Django 4.0 on 2023-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_account_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
