# Generated by Django 4.0 on 2023-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_account_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shift_end',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='shift_start',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
