# Generated by Django 4.0 on 2023-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_account_shift_end_account_shift_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shift_end',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shift_start',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
