# Generated by Django 4.0 on 2023-02-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_alter_account_shift_end_alter_account_shift_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shift_start',
            field=models.TimeField(null=True),
        ),
    ]
