# Generated by Django 4.0 on 2023-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin',
            field=models.IntegerField(null=True),
        ),
    ]
