# Generated by Django 4.0 on 2023-03-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_productdatabase_admins'),
        ('Authentication', '0014_account_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.productdatabase'),
        ),
    ]
