# Generated by Django 4.0 on 2023-03-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0016_remove_account_db_profile_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='db',
        ),
    ]
