# Generated by Django 4.0 on 2023-04-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_account_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
    ]
