# Generated by Django 4.0 on 2023-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0023_account_customers_alter_account_server_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
