# Generated by Django 4.0 on 2023-05-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0024_account_code_account_is_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='till_number',
            field=models.IntegerField(null=True),
        ),
    ]
