# Generated by Django 4.0 on 2023-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0025_account_till_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='till_number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
