# Generated by Django 4.0 on 2023-03-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0012_account_server_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account')),
            ],
        ),
    ]
