# Generated by Django 4.0 on 2023-03-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0012_account_server_code'),
        ('RevenueRecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevenueRecords',
            new_name='RevenueRecord',
        ),
    ]
