# Generated by Django 4.0 on 2023-04-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0024_account_code_account_is_company_admin'),
        ('RevenueRecords', '0002_rename_revenuerecords_revenuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='revenuerecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.account'),
        ),
    ]
