# Generated by Django 4.0 on 2023-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0004_revenuerecord_increased'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='percentage',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
