# Generated by Django 4.0 on 2023-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0005_revenuerecord_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
