# Generated by Django 4.0 on 2023-04-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0006_alter_revenuerecord_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuerecord',
            old_name='percentage',
            new_name='percent',
        ),
    ]
