# Generated by Django 4.0 on 2023-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0009_alter_revenuerecord_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuerecord',
            name='increase',
            field=models.IntegerField(null=True),
        ),
    ]
