# Generated by Django 4.0 on 2023-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0010_revenuerecord_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='increase',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
