# Generated by Django 4.0 on 2023-04-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0011_alter_revenuerecord_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='increase',
            field=models.IntegerField(null=True),
        ),
    ]
