# Generated by Django 4.0 on 2023-04-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0012_alter_revenuerecord_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuerecord',
            name='increase',
        ),
    ]
