# Generated by Django 4.0 on 2023-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RevenueRecords', '0013_remove_revenuerecord_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuerecord',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
