# Generated by Django 4.0 on 2023-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField(null=True)),
                ('amount', models.IntegerField()),
                ('server_code', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
