# Generated by Django 4.0 on 2023-03-27 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=500, null=True)),
                ('item_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=100, null=True)),
                ('admin', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='Products.Product')),
            ],
        ),
    ]
