# Generated by Django 4.0 on 2023-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_productdatabase_admin_productdatabase_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdatabase',
            name='admin',
            field=models.IntegerField(null=True),
        ),
    ]
