# Generated by Django 4.0 on 2023-03-29 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0005_alter_productdatabase_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdatabase',
            name='admin',
        ),
        migrations.AddField(
            model_name='productdatabase',
            name='admins',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
