# Generated by Django 4.0 on 2023-03-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_productdatabase_admin_productdatabase_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdatabase',
            old_name='admin',
            new_name='admins',
        ),
    ]
