# Generated by Django 4.0 on 2023-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_rename_admin_productdatabase_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdatabase',
            name='admins',
        ),
    ]
