# Generated by Django 4.0 on 2023-03-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0017_remove_profile_db'),
        ('Products', '0010_remove_productdatabase_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdatabase',
            name='access_allowed',
            field=models.ManyToManyField(null=True, to='Authentication.Profile'),
        ),
    ]
