# Generated by Django 4.0 on 2023-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0017_remove_profile_db'),
        ('Products', '0011_productdatabase_access_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdatabase',
            name='access_allowed',
        ),
        migrations.AddField(
            model_name='productdatabase',
            name='profiles',
            field=models.ManyToManyField(to='Authentication.Profile'),
        ),
    ]
