# Generated by Django 4.0 on 2023-03-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_employees_alter_productdatabase_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdatabase',
            old_name='profiles',
            new_name='employees',
        ),
    ]
