# Generated by Django 4.0 on 2023-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_alter_employees_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.TextField(null=True),
        ),
    ]
