# Generated by Django 4.0 on 2023-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_product_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productdatabase',
            name='products',
            field=models.ManyToManyField(to='Products.Product'),
        ),
    ]
